from rest_framework.views import APIView
from rest_framework.response import Response
from django.conf import settings
import httpx
import logging

logger = logging.getLogger(__name__)

class ChatAPIView(APIView):
    def post(self, request):
        prompt = request.data.get('prompt', '')
        history = request.data.get('history', [])
        system_instruction = request.data.get('system_instruction', '')

        gemini_key = getattr(settings, 'GEMINI_API_KEY', None)
        if not gemini_key:
            return Response({"error": "Gemini API key not configured"}, status=500)

        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent?key={gemini_key}"
        
        contents = []
        if history:
            for h in history:
                role = "user" if h.get("role") == "user" else "model"
                contents.append({
                    "role": role,
                    "parts": [{"text": h.get("content", "")}]
                })
        
        contents.append({
            "role": "user",
            "parts": [{"text": prompt}]
        })
        
        payload = {"contents": contents}
        
        if system_instruction:
            payload["systemInstruction"] = {
                "parts": [{"text": system_instruction}]
            }

        try:
            with httpx.Client() as client:
                resp = client.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=30.0)
                resp.raise_for_status()
                data = resp.json()
                
                candidates = data.get('candidates', [])
                if not candidates:
                    return Response({"response": "No response generated by Gemini."})
                    
                text_response = candidates[0].get('content', {}).get('parts', [{}])[0].get('text', '')
                return Response({"response": text_response})
        except Exception as e:
            logger.error(f"Gemini API error: {e}")
            return Response({"error": "Failed to communicate with AI API."}, status=500)

class DocumentAIView(APIView):
    def post(self, request):
        # Mock document extraction or call Gemini
        doc_text = request.data.get('text', '')
        return Response({
            "summary": "Document processed via Django AI API.",
            "status": "Success"
        })
