# Generated by Django 6.1 on 2026-08-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadedBy', models.CharField(max_length=255)),
                ('uploadDate', models.CharField(max_length=100)),
                ('ocrSummary', models.TextField(blank=True, null=True)),
                ('keyEntities', models.TextField(blank=True, null=True)),
                ('actionItems', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=255)),
                ('empId', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=50)),
                ('maritalDesc', models.CharField(max_length=50)),
                ('employmentStatus', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('dateOfHire', models.CharField(max_length=100)),
                ('managerName', models.CharField(max_length=255)),
                ('engagementSurvey', models.FloatField()),
                ('empSatisfaction', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('performanceScore', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ErpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('nameTranslations', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('isLowStock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ErpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('customerOrVendor', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('totalAmount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('itemDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('proof', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('requestedBy', models.CharField(max_length=255)),
                ('requestedDate', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('referenceId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
